# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\leo.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 0, 1, 1, 1)
        self.mainTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainTitleLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mainTitleLabel.setFont(font)
        self.mainTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainTitleLabel.setObjectName("mainTitleLabel")
        self.gridLayout_2.addWidget(self.mainTitleLabel, 1, 1, 1, 1)
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rawPeakCSVLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.rawPeakCSVLabel.setObjectName("rawPeakCSVLabel")
        self.gridLayout.addWidget(self.rawPeakCSVLabel, 3, 0, 1, 1)
        self.outputLocationBtn = QtWidgets.QPushButton(self.gridGroupBox)
        self.outputLocationBtn.setObjectName("outputLocationBtn")
        self.gridLayout.addWidget(self.outputLocationBtn, 4, 3, 1, 1)
        self.condensedOutputLineEdit = QtWidgets.QLineEdit(self.gridGroupBox)
        self.condensedOutputLineEdit.setReadOnly(True)
        self.condensedOutputLineEdit.setObjectName("condensedOutputLineEdit")
        self.gridLayout.addWidget(self.condensedOutputLineEdit, 5, 2, 1, 1)
        self.condensedOutputBtn = QtWidgets.QPushButton(self.gridGroupBox)
        self.condensedOutputBtn.setObjectName("condensedOutputBtn")
        self.gridLayout.addWidget(self.condensedOutputBtn, 5, 3, 1, 1)
        self.outputCSVLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.outputCSVLabel.setObjectName("outputCSVLabel")
        self.gridLayout.addWidget(self.outputCSVLabel, 4, 0, 1, 1)
        self.maxRTDiffSpinBox = QtWidgets.QDoubleSpinBox(self.gridGroupBox)
        self.maxRTDiffSpinBox.setMaximum(20.0)
        self.maxRTDiffSpinBox.setSingleStep(0.1)
        self.maxRTDiffSpinBox.setProperty("value", 2.0)
        self.maxRTDiffSpinBox.setObjectName("maxRTDiffSpinBox")
        self.gridLayout.addWidget(self.maxRTDiffSpinBox, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridGroupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 3, 1, 1)
        self.rawPeakBtn = QtWidgets.QLineEdit(self.gridGroupBox)
        self.rawPeakBtn.setEnabled(True)
        self.rawPeakBtn.setReadOnly(True)
        self.rawPeakBtn.setObjectName("rawPeakBtn")
        self.gridLayout.addWidget(self.rawPeakBtn, 3, 2, 1, 1)
        self.minMZRatioSpinBox = QtWidgets.QDoubleSpinBox(self.gridGroupBox)
        self.minMZRatioSpinBox.setMaximum(1.0)
        self.minMZRatioSpinBox.setSingleStep(0.01)
        self.minMZRatioSpinBox.setObjectName("minMZRatioSpinBox")
        self.gridLayout.addWidget(self.minMZRatioSpinBox, 1, 2, 1, 1)
        self.outputLocationLineEdit = QtWidgets.QLineEdit(self.gridGroupBox)
        self.outputLocationLineEdit.setReadOnly(True)
        self.outputLocationLineEdit.setObjectName("outputLocationLineEdit")
        self.gridLayout.addWidget(self.outputLocationLineEdit, 4, 2, 1, 1)
        self.minMZRatioLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.minMZRatioLabel.setObjectName("minMZRatioLabel")
        self.gridLayout.addWidget(self.minMZRatioLabel, 1, 0, 1, 1)
        self.minMZSpinBox = QtWidgets.QSpinBox(self.gridGroupBox)
        self.minMZSpinBox.setMaximum(1000000)
        self.minMZSpinBox.setSingleStep(10000)
        self.minMZSpinBox.setProperty("value", 50000)
        self.minMZSpinBox.setObjectName("minMZSpinBox")
        self.gridLayout.addWidget(self.minMZSpinBox, 0, 2, 1, 1)
        self.minMZLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.minMZLabel.setObjectName("minMZLabel")
        self.gridLayout.addWidget(self.minMZLabel, 0, 0, 1, 1)
        self.condensedOutputLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.condensedOutputLabel.setObjectName("condensedOutputLabel")
        self.gridLayout.addWidget(self.condensedOutputLabel, 5, 0, 1, 1)
        self.maxRTDiffLabel = QtWidgets.QLabel(self.gridGroupBox)
        self.maxRTDiffLabel.setObjectName("maxRTDiffLabel")
        self.gridLayout.addWidget(self.maxRTDiffLabel, 2, 0, 1, 1)
        self.btnWidget = QtWidgets.QWidget(self.gridGroupBox)
        self.btnWidget.setObjectName("btnWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.btnWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.viewLastBtn = QtWidgets.QPushButton(self.btnWidget)
        self.viewLastBtn.setEnabled(False)
        self.viewLastBtn.setObjectName("viewLastBtn")
        self.gridLayout_3.addWidget(self.viewLastBtn, 0, 1, 1, 1)
        self.visualizeBtn = QtWidgets.QPushButton(self.btnWidget)
        self.visualizeBtn.setEnabled(False)
        self.visualizeBtn.setObjectName("visualizeBtn")
        self.gridLayout_3.addWidget(self.visualizeBtn, 0, 0, 1, 1)
        self.parseBtn = QtWidgets.QPushButton(self.btnWidget)
        self.parseBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.parseBtn.setObjectName("parseBtn")
        self.gridLayout_3.addWidget(self.parseBtn, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.btnWidget, 6, 2, 2, 1)
        self.gridLayout_2.addWidget(self.gridGroupBox, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEO"))
        self.mainTitleLabel.setText(_translate("MainWindow", "Leo"))
        self.rawPeakCSVLabel.setText(_translate("MainWindow", "Raw Peak CSV"))
        self.outputLocationBtn.setText(_translate("MainWindow", "Pick Location"))
        self.condensedOutputBtn.setText(_translate("MainWindow", "Pick Location"))
        self.outputCSVLabel.setText(_translate("MainWindow", "Output CSV"))
        self.maxRTDiffSpinBox.setToolTip(_translate("MainWindow", "Max difference from expeceted retention time."))
        self.pushButton_4.setText(_translate("MainWindow", "Pick Location"))
        self.minMZRatioSpinBox.setToolTip(_translate("MainWindow", "Minimum ratio difference between test times."))
        self.minMZRatioLabel.setText(_translate("MainWindow", "Min MZ Ratio"))
        self.minMZSpinBox.setToolTip(_translate("MainWindow", "Minimum intensity/"))
        self.minMZLabel.setText(_translate("MainWindow", "Min MZ"))
        self.condensedOutputLabel.setText(_translate("MainWindow", "Condensed Output CSV"))
        self.maxRTDiffLabel.setText(_translate("MainWindow", "Max RT Diff"))
        self.viewLastBtn.setText(_translate("MainWindow", "View Last Parse"))
        self.visualizeBtn.setText(_translate("MainWindow", "Visualize Last Parse"))
        self.parseBtn.setText(_translate("MainWindow", "Parse"))

